<?php
/**
 * Product
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Ced
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mirakl Connect APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: afcae4e6-28a6-4477-a8ed-d78442ed50d5
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Ced\Model;

use \ArrayAccess;
use \Ced\ObjectSerializer;

/**
 * Product Class Doc Comment
 *
 * @category Class
 * @package  Ced
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Product implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Product';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'gtins' => '\Ced\Model\Gtin[]',
        'standard_prices' => '\Ced\Model\StandardPrice[]',
        'discount_prices' => '\Ced\Model\DiscountPrice[]',
        'quantities' => '\Ced\Model\Quantity[]',
        'images' => '\Ced\Model\Image[]',
        'titles' => '\Ced\Model\Title[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'gtins' => null,
        'standard_prices' => null,
        'discount_prices' => null,
        'quantities' => null,
        'images' => null,
        'titles' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
		'gtins' => false,
		'standard_prices' => false,
		'discount_prices' => true,
		'quantities' => false,
		'images' => true,
		'titles' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'gtins' => 'gtins',
        'standard_prices' => 'standard_prices',
        'discount_prices' => 'discount_prices',
        'quantities' => 'quantities',
        'images' => 'images',
        'titles' => 'titles'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'gtins' => 'setGtins',
        'standard_prices' => 'setStandardPrices',
        'discount_prices' => 'setDiscountPrices',
        'quantities' => 'setQuantities',
        'images' => 'setImages',
        'titles' => 'setTitles'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'gtins' => 'getGtins',
        'standard_prices' => 'getStandardPrices',
        'discount_prices' => 'getDiscountPrices',
        'quantities' => 'getQuantities',
        'images' => 'getImages',
        'titles' => 'getTitles'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('gtins', $data ?? [], null);
        $this->setIfExists('standard_prices', $data ?? [], null);
        $this->setIfExists('discount_prices', $data ?? [], null);
        $this->setIfExists('quantities', $data ?? [], null);
        $this->setIfExists('images', $data ?? [], null);
        $this->setIfExists('titles', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['id']) && (mb_strlen($this->container['id']) > 256)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['id']) && (mb_strlen($this->container['id']) < 1)) {
            $invalidProperties[] = "invalid value for 'id', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['gtins']) && (count($this->container['gtins']) > 10)) {
            $invalidProperties[] = "invalid value for 'gtins', number of items must be less than or equal to 10.";
        }

        if (!is_null($this->container['gtins']) && (count($this->container['gtins']) < 0)) {
            $invalidProperties[] = "invalid value for 'gtins', number of items must be greater than or equal to 0.";
        }

        if (!is_null($this->container['standard_prices']) && (count($this->container['standard_prices']) > 10)) {
            $invalidProperties[] = "invalid value for 'standard_prices', number of items must be less than or equal to 10.";
        }

        if (!is_null($this->container['standard_prices']) && (count($this->container['standard_prices']) < 1)) {
            $invalidProperties[] = "invalid value for 'standard_prices', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['discount_prices']) && (count($this->container['discount_prices']) > 10)) {
            $invalidProperties[] = "invalid value for 'discount_prices', number of items must be less than or equal to 10.";
        }

        if (!is_null($this->container['quantities']) && (count($this->container['quantities']) > 1)) {
            $invalidProperties[] = "invalid value for 'quantities', number of items must be less than or equal to 1.";
        }

        if (!is_null($this->container['quantities']) && (count($this->container['quantities']) < 1)) {
            $invalidProperties[] = "invalid value for 'quantities', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['images']) && (count($this->container['images']) > 1)) {
            $invalidProperties[] = "invalid value for 'images', number of items must be less than or equal to 1.";
        }

        if (!is_null($this->container['images']) && (count($this->container['images']) < 0)) {
            $invalidProperties[] = "invalid value for 'images', number of items must be greater than or equal to 0.";
        }

        if (!is_null($this->container['titles']) && (count($this->container['titles']) > 1)) {
            $invalidProperties[] = "invalid value for 'titles', number of items must be less than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Product identifiers in the catalog you want to import
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        if ((mb_strlen($id) > 256)) {
            throw new \InvalidArgumentException('invalid length for $id when calling Product., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $id when calling Product., must be bigger than or equal to 1.');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets gtins
     *
     * @return \Ced\Model\Gtin[]|null
     */
    public function getGtins()
    {
        return $this->container['gtins'];
    }

    /**
     * Sets gtins
     *
     * @param \Ced\Model\Gtin[]|null $gtins All Global Trade Item Numbers are accepted: EAN, GENCOD, UPC, ISBN… GTINs are used to map your products with those of the marketplace catalog.
     *
     * @return self
     */
    public function setGtins($gtins)
    {
        if (is_null($gtins)) {
            throw new \InvalidArgumentException('non-nullable gtins cannot be null');
        }

        if ((count($gtins) > 10)) {
            throw new \InvalidArgumentException('invalid value for $gtins when calling Product., number of items must be less than or equal to 10.');
        }
        if ((count($gtins) < 0)) {
            throw new \InvalidArgumentException('invalid length for $gtins when calling Product., number of items must be greater than or equal to 0.');
        }
        $this->container['gtins'] = $gtins;

        return $this;
    }

    /**
     * Gets standard_prices
     *
     * @return \Ced\Model\StandardPrice[]|null
     */
    public function getStandardPrices()
    {
        return $this->container['standard_prices'];
    }

    /**
     * Sets standard_prices
     *
     * @param \Ced\Model\StandardPrice[]|null $standard_prices Standard prices of products only (no discount prices).
     *
     * @return self
     */
    public function setStandardPrices($standard_prices)
    {
        if (is_null($standard_prices)) {
            throw new \InvalidArgumentException('non-nullable standard_prices cannot be null');
        }

        if ((count($standard_prices) > 10)) {
            throw new \InvalidArgumentException('invalid value for $standard_prices when calling Product., number of items must be less than or equal to 10.');
        }
        if ((count($standard_prices) < 1)) {
            throw new \InvalidArgumentException('invalid length for $standard_prices when calling Product., number of items must be greater than or equal to 1.');
        }
        $this->container['standard_prices'] = $standard_prices;

        return $this;
    }

    /**
     * Gets discount_prices
     *
     * @return \Ced\Model\DiscountPrice[]|null
     */
    public function getDiscountPrices()
    {
        return $this->container['discount_prices'];
    }

    /**
     * Sets discount_prices
     *
     * @param \Ced\Model\DiscountPrice[]|null $discount_prices Discount prices of products. Set this field to null to remove all discount prices.
     *
     * @return self
     */
    public function setDiscountPrices($discount_prices)
    {
        if (is_null($discount_prices)) {
            array_push($this->openAPINullablesSetToNull, 'discount_prices');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('discount_prices', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($discount_prices) && (count($discount_prices) > 10)) {
            throw new \InvalidArgumentException('invalid value for $discount_prices when calling Product., number of items must be less than or equal to 10.');
        }
        $this->container['discount_prices'] = $discount_prices;

        return $this;
    }

    /**
     * Gets quantities
     *
     * @return \Ced\Model\Quantity[]|null
     */
    public function getQuantities()
    {
        return $this->container['quantities'];
    }

    /**
     * Sets quantities
     *
     * @param \Ced\Model\Quantity[]|null $quantities Product quantities
     *
     * @return self
     */
    public function setQuantities($quantities)
    {
        if (is_null($quantities)) {
            throw new \InvalidArgumentException('non-nullable quantities cannot be null');
        }

        if ((count($quantities) > 1)) {
            throw new \InvalidArgumentException('invalid value for $quantities when calling Product., number of items must be less than or equal to 1.');
        }
        if ((count($quantities) < 1)) {
            throw new \InvalidArgumentException('invalid length for $quantities when calling Product., number of items must be greater than or equal to 1.');
        }
        $this->container['quantities'] = $quantities;

        return $this;
    }

    /**
     * Gets images
     *
     * @return \Ced\Model\Image[]|null
     */
    public function getImages()
    {
        return $this->container['images'];
    }

    /**
     * Sets images
     *
     * @param \Ced\Model\Image[]|null $images Images associated with products.  The image URL is required for http or https protocoles. Only one image per product is allowed. An example of a correct image URL is : http://my_image.png or https://my_image.png
     *
     * @return self
     */
    public function setImages($images)
    {
        if (is_null($images)) {
            array_push($this->openAPINullablesSetToNull, 'images');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('images', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($images) && (count($images) > 1)) {
            throw new \InvalidArgumentException('invalid value for $images when calling Product., number of items must be less than or equal to 1.');
        }
        if (!is_null($images) && (count($images) < 0)) {
            throw new \InvalidArgumentException('invalid length for $images when calling Product., number of items must be greater than or equal to 0.');
        }
        $this->container['images'] = $images;

        return $this;
    }

    /**
     * Gets titles
     *
     * @return \Ced\Model\Title[]|null
     */
    public function getTitles()
    {
        return $this->container['titles'];
    }

    /**
     * Sets titles
     *
     * @param \Ced\Model\Title[]|null $titles Title with its associated locale that is displayed in the catalog. Set this field to null to remove the title.
     *
     * @return self
     */
    public function setTitles($titles)
    {
        if (is_null($titles)) {
            array_push($this->openAPINullablesSetToNull, 'titles');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('titles', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($titles) && (count($titles) > 1)) {
            throw new \InvalidArgumentException('invalid value for $titles when calling Product., number of items must be less than or equal to 1.');
        }
        $this->container['titles'] = $titles;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


